# Generated by Django 3.1.1 on 2020-09-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='show this ?')),
                ('position', models.IntegerField(verbose_name='position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
